"""create auctions table with uuid

Revision ID: 8382d28f945a
Revises: 
Create Date: 2026-04-28 01:23:35.339855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8382d28f945a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('seller_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reserve_price_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('reserve_price_currency', sa.String(length=3), nullable=True),
    sa.Column('minimum_percentage', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('product_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('winner_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_id'), 'auctions', ['id'], unique=False)
    op.create_index(op.f('ix_auctions_seller_id'), 'auctions', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_seller_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_id'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
