name: CI - Automated Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Dependency install
      run: poetry install

    - name: Run Pytest
      run: poetry run pytest tests/ -v
